
---
title: "Welcome"
html_document:
output:
  html_document:
    toc: true
    toc_float: true
---


Welcome to BIOL 3140, Experimental Methods in Organismal Biology!!! 

Organismal biology is the study of living systems of all scales that shape the structure, function, ecology, and evolution of individual organisms. Experiments that elucidate how organisms respond to biotic and abiotic environmental stimulus over broad time scales—from changes in behavior to adaptation—are crucial to understanding biological diversity. In this course we’ll explore the concepts and experimental and analytical tools that frame research in organismal biology. Through group projects and active learning exercises, students will make hypotheses concerning how organisms respond in time, space, and behavior to changes in environment and then design experiments and instruments that produce data to evaluate these hypotheses. Topics covered will include reconstructing phylogenetic history and the evolution of organismal form and function, evaluating form-function relationships, and the correlates of spatial and temporal distribution of organisms. In addition, the development of an analytical toolbox—specifically, learning the principles of data science and statistical analysis—is a central theme of this course.

# Course scope, goals, and objectives

To be an effective organismal biologist, one we must prepare, analyze, visualize, and communicate data as we formulate answers to the questions we're asking. Despite the importance of these technological skills to our discipline, students often see the acquisition and analysis of data as technological black boxes. Countless times in previous course, instructors have no doubt demonstrated foundational principles and concepts through the presentation of data, usually through figures in papers or lecture slides. However, where these data come from and how they have answered a question remain often remain a mystery. In turn, students must to rely on the authority of their instructors rather than their own grasp of the quantitative skills and data collection to make meaningful connections.

As a course-based research experience, BIOL 3140 is meant to develop and hone skills related to instrumentation and data science in the context of organismal biology. The thrust of this course will center around the development of simple sensor-data acquisition systems and the analysis of data collected from them. Through hands-on design and fabrication of sensor-based instrument prototypes representing models of more complex instrumentation, students will develop a direct relationship with the source of data in scientific research. 

## Course goals and objectives

With respect to instrumentation, the learning goals of this program include:

1.	Understanding of how common sensors convert physical phenomena into electrical signals.
2.	Familiarity with the basics of signal conditioning, amplification, and the conversion of sensor signals into a form that can be converted into digital values.
3.	Understanding the basics of analog-to-digital conversion and digital signal acquisition.
4.	Development of basic programming skills that permit flexible repurposing of a common data-acquisition system.
 
The specific learning objectives of our instrumentation work include:
 
1.	Development of 3 instruments which detect temperature, force, and acceleration in human subjects.
2.	Assembly and programming of an Arduino-based data-acquisition system to process and condition signals from a variety of sensor types.
 
For students in the natural sciences, perhaps more important than understanding how data is acquired is understanding how to analyze data in the context of answering a specific question. To this end, we will pursue the following data science learning goals that include:
 
1.	Learning how to import data into a computing environment.
2.	Understanding basic tidying and transforming (i.e., wrangling) operations of data to answer scientific questions.
3.	Developing competency in basic data visualization.
4.	Learning how to model data in the context of answering a scientific question.
5.	Executing the critical basics of communication in a data science framework.
                                  
All of these data-science learning goals will be realized in the framework of the R computing environment. Using R, students will open the black box of data analysis and pursue these specific objectives:
           
1.	Import, tidy, and transform sensor data so that specific scientific questions can be asked.
2.	Visualize sensor data in the R environment using ggplot, an elegant and versatile tool for data visualization.
3.	Evaluate a-priori scientific questions within a modeling framework, rejecting or accepting hypotheses according to model expectations.
4.	Report answers in concise reports, leveraging R's fast and reproducible markdown capabilities.

# Course requirements
Read: https://r4ds.had.co.nz/introduction.html
Read: https://rstudio-education.github.io/hopr/

# Course assessment

How grades will be determined.

# Course outline

## Phase I: Didactic Head Banging

In this phase, we'll learn the basics of instrumentation and data analysis by working through XX learning modules devoted to instrument design and data analysis. This will most likely be the most challenging part of the course in that many, if not most of you will not have ever designed and built instruments and data acquisition systems, let alone analyzed data from them. Rest assured, your experience will be curated, sticking to the bare bones of instrument design and data science. This introductory phase will set the groundwork for Phase II, the independent development of sensors and data analysis.

Module include:

  1. **Cheap Tricks in Physiology:** Designing and Programming Simple, Low-Cost Data Acquisition Systems
  2. **Data Wrangling:** Introduction to Tools of the Trade in Data Analysis
  3. **The Whiz and Viz Bang of Data:** The Basics of Data Visualizations and Modeling
  4. **Making Messes Pretty:** Leveraging Markdown to Produce Pleasing Reports

## Phase II: Thrown to the Wolves

In Phase II, we'll use our new-found instrument- and code-development skills to address key questions in organismal biology. These will be largely independent explorations of instrument design and use and data analysis meant to challenge you to put these skills to good use in answering how vertebrates muscles work, how size and phylogeny matters in physiological systems, and how a changing climate impacts the distribution of vertebrates. Within this phase we'll focus on 4 modules, some data driven, the others both data and instrument driven, including:

  1. **Birds of a Feather Migrate Together, Sometimes:** Using EBird data to Explore the Phenology of Passerine Migration (auk package from R) (data driven)
  2. **Beach Muscles:** Exploring Force-Length Relationships in Vertebrate Muscle (instrument and data driven)
  3. **Hot Flashes I:** Scaling the Diel Temperature Oscillations in Mammals (instrument and data driven)
  4. **Hot Flashes II:** Not So Fast! Correcting Scaling Models Withing a Phylogenetic Context (data driven)
  5. **Jumping UGs**: Testing the Limits of Human Lower Body Power (instrument and data driven)

## Phase III: Unleashing Your Inner Scientist

In Phase III, you'll be tasked with quickly developing a project of your own design that requires the fabrication of a new or modified data acquisition system 
