<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Module 8 Project</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/sandstone.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/accessible-code-block-0.0.1/empty-anchor.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 61px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h2 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h3 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h4 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h5 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h6 {
  padding-top: 66px;
  margin-top: -66px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">BIOL 3140</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="schedule.html">Schedule</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Phase I</li>
    <li>
      <a href="phaseI_rubric.html">Phase I report rubric</a>
    </li>
    <li>
      <a href="mod1_proj.html">Module 1 Project</a>
    </li>
    <li>
      <a href="mod2_proj.html">Module 2 Project</a>
    </li>
    <li>
      <a href="mod3_proj.html">Module 3 Project</a>
    </li>
    <li>
      <a href="mod4_proj.html">Module 4 Project</a>
    </li>
    <li>
      <a href="mod5_proj.html">Module 5 Project</a>
    </li>
    <li class="dropdown-header">Phase II</li>
    <li>
      <a href="phaseII_rubric.html">Phase II report rubric</a>
    </li>
    <li>
      <a href="mod6_proj.html">Module 6 Project</a>
    </li>
    <li>
      <a href="mod7_proj.html">Module 7 Project</a>
    </li>
    <li>
      <a href="mod8_proj.html">Module 8 Project</a>
    </li>
    <li>
      <a href="mod9_proj.html">Module 9 Project</a>
    </li>
    <li class="dropdown-header">Phase III</li>
    <li>
      <a href="phaseIII_rubric.html">Phase III report rubric</a>
    </li>
    <li>
      <a href="final_proj.html">Final Project</a>
    </li>
    <li class="dropdown-header">DaqPacks</li>
    <li>
      <a href="daqpack.html">DaqPack Item List</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://github.com/orgs/bcorgbio/teams/biol3140_f21">BIOL 3140 Discussion</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Module 8 Project</h1>

</div>


<style>
div.green { background-color:#c7d1c0; border-radius: 5px; padding: 20px;}
</style>
<!-- Add icon library -->
<p><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"></p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Any student steeped in the mechanics of muscle understands that force produced by this tissue is governed by two important parameters: speed and length. In this project, we’ll explore the effect of length on muscle force generation and evaluate how fatigue affects this force-length (FL) relationship.</p>
<p>The FL relationship is governed by several important biophysical aspects of muscle architecture. At the fiber level, the force produced is largely mediated by the number of crossbridges that can be formed. Crossbridges are small and have a limited attachment range. Therefore, crossbridge attachments only occur in the actin-myosin overlap zone of a sarcomere. Together with the assumptions underlying the crossbridge theory, this limitation implies that the maximal isometric force of a sarcomere is directly related to the amount of actin-myosin overlap (Fig. 1).</p>
<center>
<img src="https://journals.physiology.org/cms/10.1152/jappl.1999.86.5.1445/asset/images/medium/japp05516002x.jpeg" /> <br> <strong>Fig. 1.</strong> The force-length relationship of a sarcomere as predicted by cross-bridge theory.
</center>
<p><br></p>
<p>Of course, many muscles transect a lever system composed of a few bones articulating at a joint. For our subject, the human upper limb, the forearm flexors originate on the pectoral girdle above the humerus and insert on the radius and ulna, spanning the elbow joint. Simply put, the arm is a 3rd order lever (Fig 2). If we are to consider the force transmitted to the hand (or any other part along the antebrachium), we must also consider this lever configuration. As a lever, this system has a mechanical advantage that predicts the amount of output force transmitted by the input force. Mechanical advantage is defined by the following:</p>
<p><span class="math display">\[MA=\frac{L_i}{L_o}\]</span>,</p>
<p>where <span class="math inline">\(L_i\)</span> is the in-lever and <span class="math inline">\(L_o\)</span> the output leaver. For the human upper limb, the inlever is the distance between the flexor insertion and elbow joint and the out-lever is the length of the antebrachium and hand (or the distance between the elbow and the load). This ratio generally accords to 0.2 in this system. What this predicts is that any force applied to the in-lever results in 20% of that force at the end of the out-lever (i.e., the palm).</p>
<p>What makes this more complicated is that the effective in-lever, the input moment arm, changes as the forearm flexes. This is due to the fact that the insertion angle changes as the forearm rotates (Fig. 3). Because the force produced by an input is variable with respect to insertion angle, the output isn’t necessarily predicted by MA alone.</p>
<center>
<p><img src="https://openoregon.pressbooks.pub/app/uploads/sites/42/2018/07/Range-300x262.png" /></p>
<strong>Fig. 2</strong> The 3rd-order level system of the human upper limb.
</center>
<p><br></p>
<p>Fortunately for us, physiologists have found that studying the force (or torque) produced by a biomechanical system can still be useful in uncovering the FL relationships of the input muscles <span class="citation">(Rassier, MacIntosh, and Herzog 1999)</span>. For this project, we take this assumption to mean that the force we measure at the hand as the muscle produces isometric force at various lengths is a reasonable reflection of the FL relationship governing force at the fiber level.</p>
<center>
<img src="arm.gif" /> <br> <strong>Fig. 4.</strong> Rotation of the forearm through its typical range of motion. Notice that the insertion angle of the biceps changes. (This was of course produced with R . . . have a look at <a href="https://gist.github.com/ckenaley/924171571a73874384a6aaaef93e372b">this gist on github</a> if you’d like the code.)
</center>
<p><br></p>
<p>Keeping all this mind mind, we’ll study the FL relationship of the human upper limb and how this relationship responds to fatigue. Eccentric fatigue, whereby the muscle has been asked to do a lot of negative work (producing tension while lengthening) has been a particular interested to muscle physiologists <span class="citation">(Yeung and Yeung 2008)</span>. That is, this research has shown that the force/torque-length/angle relationship shifts soon after and long after eccentric fatigue. Specifically, the peak normalized isometric force shifts over the typical range of angles for a biomechanical system.</p>
<p>The specific goals of this project are to:</p>
<ol style="list-style-type: decimal">
<li>Produce isometric force-angle curves for the human forearm flexors undertaking maximum voluntary contractions (MVCs).</li>
<li>Compare the angle at which maximum isometric force (<span class="math inline">\(F_{max}\)</span>) occurs (<span class="math inline">\(\theta_{max}\)</span>) between non-fatigued (i.e., control) and eccentrically fatigued forearm flexors.</li>
<li>Discuss the underlying mechanisms resulting in a shift of <span class="math inline">\(\theta_{max}\)</span> after eccentric fatigue.</li>
</ol>
</div>
<div id="methods" class="section level1">
<h1>Methods</h1>
<div id="experimental-design" class="section level2">
<h2>Experimental Design</h2>
<p>To assess the affect of eccentric fatigue of elbow flexor muscles, we’ll be measuring the isometric force over the range of motion of the forearm produced by MVC. To capture MVC data, you must design and construct a portable Arduino-based force-data acquisition system (DAQ). Your device should record force data over the course of 30s.</p>
</div>
<div id="daq-design-components" class="section level2">
<h2>DAQ Design Components</h2>
<ol style="list-style-type: decimal">
<li>40-kg Load Cell with HX711 amplifier</li>
<li>Arduino Uno microcontroller</li>
</ol>
</div>
<div id="daq-assembly-and-programming" class="section level2">
<h2>DAQ Assembly and Programming</h2>
<p>Assembly for this force logger is almost entirely captured in <a href="https://www.instructables.com/Arduino-Tension-Scale-With-40-Kg-Luggage-Load-Cell/">this tutorial</a>.</p>
<p>You’ll see that the sketch in the tutorial requires a calibration step to output appropriate force or mass units. <strong>Don’t worry about calibration.</strong> We’ll be looking a normalized force, so units don’t matter.</p>
<!-- As for your SD storage integration, make sure your sketch writes one column data to the SD card with the header "force". -->
<p>For each experiment, you’ll be recording 12 bouts of MVC force, each corresponding to a different elbow angle, for 30 s. For each arm angle, one only needs to unplug the Arduino and hit the red restart button on the Arduino to begin taking force data. So as not to confuse from where your data came, it’s a good idea to change the name of the text file being saved to for each experiment, e.g., “Subject1_control.csv” and “Subject1_fatigue.csv”.</p>
</div>
<div id="data-collection" class="section level2">
<h2>Data Collection</h2>
<div id="elbow-angle" class="section level3">
<h3>Elbow Angle</h3>
<p>You’ll first need to construct a ganiometer, a simple device that measures the angle between the upper and lower arm (i.e., the elbow angle). One approach is to use the outline of a small plate to cut a disc out of cardboard and then bisect the diameter and then continue to bisect this semicircle into equal segments (Fig. 4.)</p>
<center>
<img src="gan.jpg" style="width:50.0%" /> <br> <strong>Fig. 4</strong> A simple ganiometer made of cardboard.
</center>
<p><br></p>
<p>To use the ganiometer, find the center of the elbow joint in lateral view and mark this position with a marker. From this point, mark a line along the lateral margin of the radius. (Fig. 5). Then, poke a hole through the center of the ganiometer and affix it to the upper arm so its center aligns with your mark at the elbow joint and the 0-180<span class="math inline">\(^o\)</span> axis aligns with the long axis of the humerus (Fig. 6).You can affix the ganiometer to the upper arm by passing a strip of surgical tape through two tabs cut out on either side of the 0-180<span class="math inline">\(^o\)</span> axis (Fig. 6).</p>
<center>
<img src="joint.jpg" style="width:50.0%" /> <br> <strong>Fig. 4</strong> The elbow joint on a tiny human and the lateral margin of the radius marked with a dark line. Thanks, Zo!
</center>
<p><br></p>
<center>
<img src="90deg.jpg" style="width:50.0%" /> <br> <strong>Fig. 5</strong> The ganiometer affixed to the upper arm with surgical tape with its center placed over the elbow joint. Note how the marked line on the radius indicates an elbow angle of about 90<span class="math inline">\(^o\)</span>.
</center>
<p><br></p>
<p>As the elbow flexes or extends, you should be able to peak at the ganiometer to assess elbow angle.</p>
</div>
<div id="isometric-mvcs" class="section level3">
<h3>Isometric MVCs</h3>
<p>We will collect isometric force data from MVCs over 12 arm angles, 45-157.5<span class="math inline">\(^o\)</span> at 11.25<span class="math inline">\(^o\)</span> (call it 11<span class="math inline">\(^o\)</span>) intervals. Your load-cell is affixed to two hooks. Attach one hook to the dowel in your DAQ pack and the other to something that won’t move under the torque of your forearm. This could be a table, chair, bench, etc. Hold the dowel in your hand as shown in Fig. 6. Make sure your elbow is supported by something rigid (i.e. the top of a chair back, etc.).</p>
<center>
<img src="grip.jpg" style="width:50.0%" /> <br> <strong>Fig. 6</strong> How to grip the the load-cell.
</center>
<p><br></p>
<p>First collect your control (i.e., non-fatigued) data by starting at the largest arm angle, 157.5<span class="math inline">\(^o\)</span>. You can move through the 12 arm angles by rotating your body about your hips. That is, at the high elbow angles, you’ll be more upright, at lower angles, more bent over. At each angle, flex your elbow as hard as you can to produce a MVC, resetting your DAQ system each time. Make sure the load-cell forms a right angle with reference to your hand (Fig. 6). You might want to practice a few times to get a sense of how this will proceed.</p>
</div>
<div id="mvcs-after-eccentric-fatigue" class="section level3">
<h3>MVCs after Eccentric Fatigue</h3>
<p>To eccentrically fatigue your forearm flexors, you’ll perform isokinetic controlled drops of a heavy object weighing 1/3 your maximum isometric force recorded in the control experiments. A book bag or back pack full of heavy items (ahhh. . . books) should do just fine.</p>
<p>To perform your isokinetic eccentric drops, grab the book bag with the hand not involved in the experiment and pass it to the other as its forearm is fully flexed. With the bag now in your study hand, lower the bag slowly and at a constant speed. When the arm is fully extended, grab the book bag with the free hand and then flex the study forearm. Repeat by passing the bag to your study hand. Continue repeating this exercise for 3 min. Keep the cycles uniformly frequent by monitoring the duration (probably 3-4 s each cycle). At the end of the 3 mins, your forearm flexors should feel tired.</p>
<p>After you fatigue your flexors, wait 2 min. Then repeat the experiment exactly as you did for the control data.</p>
<p>Once you complete your experiments, upload your 24 data files to <a href="https://drive.google.com/drive/folders/17KPrL6-LNnpwaA6o7fOHIMLUjbY8mcnT?usp=sharing">this Google directory</a>. Be sure to name your files according to the following convention: “team_subject_angle_control/fatigue.csv”. Please stick to all lower case.</p>
</div>
</div>
<div id="summary-of-experimental-protocol" class="section level2">
<h2>Summary of Experimental Protocol</h2>
<ul>
<li>Fabricate and program a load-cell data acquisition system.</li>
<li>Make a ganiometer.</li>
<li>Record isometric MVCs at 12 distinct elbow angles.</li>
<li>Eccentrically fatigue your flexors.</li>
<li>Wait 2 minutes.</li>
<li>Repeat recording isometric MVCs at the same 12 distinct elbow angles.</li>
<li>Upload data to <a href="https://drive.google.com/drive/folders/17KPrL6-LNnpwaA6o7fOHIMLUjbY8mcnT?usp=sharing">this directory</a>.</li>
</ul>
</div>
<div id="data-analysis" class="section level2">
<h2>Data Analysis</h2>
<p>For each experiment, we’ll stick to a convention within the muscle physiology world by considering maximum normalized force. That is:</p>
<ol style="list-style-type: decimal">
<li>Find maximum force for each recording (don’t worry about the specific values or units because you’ll. . .).</li>
<li>Find maximum force (<span class="math inline">\(F_{max}\)</span>) across all angles for each experiment (control or fatigued) for each individual and then divide all maximum values for that experiment by <span class="math inline">\(F_{max}\)</span>. Your values will now be normalize, i.e., scaled 0-1 with a value of 1 representing the highest force recorded during an experiment.</li>
</ol>
<p>Using the normalized force data from the control and fatigued experiments, we’ll consider shifts at which angle <span class="math inline">\(F_{max}\)</span> occurred, the difference in <span class="math inline">\(\theta_{max}\)</span>. To assess any shift in <span class="math inline">\(\theta_{max}\)</span> with our limited elbow angle samples, we could simply look at the angle at which the flexors produce the most force. For instance, for the these data:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2"></a>ang &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">45</span>,<span class="fl">168.75</span>,<span class="dt">length.out =</span> <span class="dv">12</span>) <span class="co">#elbow angle</span></span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a>normF &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.71</span>, <span class="fl">0.77</span>, <span class="fl">0.83</span>, <span class="fl">0.91</span>, <span class="fl">0.97</span>, <span class="fl">1.00</span>, <span class="fl">0.96</span>, <span class="fl">0.94</span>, <span class="fl">0.89</span>, <span class="fl">0.84</span>, <span class="fl">0.77</span>, <span class="fl">0.74</span>) <span class="co">#you&#39;ll get this by reading in data and calculating normalized values</span></span>
<span id="cb1-5"><a href="#cb1-5"></a></span>
<span id="cb1-6"><a href="#cb1-6"></a></span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="kw">qplot</span>(ang,normF)<span class="op">+</span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x=</span>ang[<span class="kw">which.max</span>(normF)],<span class="dt">y=</span>normF[<span class="kw">which.max</span>(normF)]),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">size=</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="mod8_proj_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>ang[<span class="kw">which.max</span>(normF)] <span class="co">#Find angle for Fmax, theta_max</span></span></code></pre></div>
<pre><code>## [1] 101.25</code></pre>
<p>So, of the 12 angles that we sampled (45–157.5<span class="math inline">\(^o\)</span>), the maximum isometric force occurred at angle (<span class="math inline">\(\theta_{max}\)</span>=) 101.25<span class="math inline">\(^o\)</span>. Simply doing this overlooks the fact that the maximum force could have occurred between any two of the sampled angles. Given the trend in the figure above, <span class="math inline">\(\theta_{max}\)</span> could have been an angle either greater and less than 101.25<span class="math inline">\(^o\)</span>. To estimate the trend and find a perhaps more refined estimation of <span class="math inline">\(F_{max}\)</span> we’ll resort to (wait for it) . . . modeling. In this case, a series of <a href="https://en.wikipedia.org/wiki/Polynomial_regression">polynomial models</a> should work. Polynomial models are great for fitting parabolic data like those we have here, but are tricky in that one can keep adding monomial terms very quickly to achieve a better fit. This requires the practitioner to make sure that they are not overfitting the model. Fortunately, we have the tools to prevent such a thing using AIC, as we have learned.</p>
<p>Therefore, let’s fit some polynomial models to our example data with a different number of monomial terms (i.e., orders) and tease apart the fit and penalty for including more terms using AICc. Fortunately, we can use the <code>lm()</code> and <code>poly()</code> functions from the base package to fit the models and use <code>AICc()</code> from the <code>MuMIn</code> package for AICc fitting.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="kw">library</span>(MuMIn)</span>
<span id="cb4-2"><a href="#cb4-2"></a></span>
<span id="cb4-3"><a href="#cb4-3"></a>poly.m2 &lt;-<span class="st"> </span><span class="kw">lm</span>(normF<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">2</span>)) <span class="co">#second order</span></span>
<span id="cb4-4"><a href="#cb4-4"></a>poly.m3 &lt;-<span class="st"> </span><span class="kw">lm</span>(normF<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">3</span>)) <span class="co">#third order</span></span>
<span id="cb4-5"><a href="#cb4-5"></a>poly.m4 &lt;-<span class="st"> </span><span class="kw">lm</span>(normF<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">4</span>)) <span class="co">#fourth order</span></span>
<span id="cb4-6"><a href="#cb4-6"></a></span>
<span id="cb4-7"><a href="#cb4-7"></a><span class="kw">AICc</span>(poly.m2,poly.m3,poly.m4) <span class="co">#the second order model fits best</span></span></code></pre></div>
<pre><code>##         df      AICc
## poly.m2  4 -43.90316
## poly.m3  5 -39.60496
## poly.m4  6 -49.47748</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>x.pred &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">45</span>,<span class="fl">157.5</span>,<span class="dt">length.out =</span> <span class="dv">1000</span>) <span class="co">#define 1000 angles from our range</span></span>
<span id="cb6-2"><a href="#cb6-2"></a></span>
<span id="cb6-3"><a href="#cb6-3"></a>normF.pred &lt;-<span class="st"> </span><span class="kw">predict</span>(poly.m4,<span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">ang=</span>x.pred)) <span class="co">#predict the force using 1000 angles</span></span>
<span id="cb6-4"><a href="#cb6-4"></a></span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="kw">qplot</span>(ang,normF)<span class="op">+</span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x.pred,<span class="dt">y=</span>normF.pred),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)<span class="op">+</span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x.pred[<span class="kw">which.max</span>(normF.pred)],<span class="dt">y=</span>normF.pred[<span class="kw">which.max</span>(normF.pred)]),<span class="dt">size=</span><span class="dv">5</span>,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="mod8_proj_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>x.pred[<span class="kw">which.max</span>(normF.pred)] <span class="co">#theta_max</span></span></code></pre></div>
<pre><code>## [1] 104.9099</code></pre>
<p>In this example we constructed 3 polynomial models of the 2nd, 3rd, 4th variety and then used AICc to find the lowest AICc score. The 4th order model fits best, so we then produced 1000 discrete values within our range with <code>seq()</code> to pass to<code>predict()</code> to predict force over this range using our best fitting model (producing <code>normF.pred</code>). We then found the max of <code>normF.pred</code> (the <span class="math inline">\(F_{max}\)</span>) and plotted that, along with our predictions. Lastly, we found <span class="math inline">\(\theta_{max}\)</span>, a value of 104.9.</p>
<p>A goal of this project is to detect shifts in <span class="math inline">\(F_{max}\)</span> with respect to angle. If we had two data sets, one control and one produced after fatigue, we merely need to compare the two <span class="math inline">\(\theta_{max}\)</span>, that is, the shift in angle for <span class="math inline">\(F_{max}\)</span> predicted by two polynomial models. This would look something like this:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>normF.fat &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.65</span>, <span class="fl">0.71</span>, <span class="fl">0.81</span>, <span class="fl">0.89</span>,<span class="fl">0.92</span>, <span class="fl">0.96</span>, <span class="fl">0.99</span>, <span class="dv">1</span>, <span class="fl">0.96</span>, <span class="fl">0.92</span>, <span class="fl">0.84</span>, <span class="fl">0.77</span>) <span class="co">#fatigue data, you&#39;ll get this by reading in data and calculating normalized values</span></span>
<span id="cb9-2"><a href="#cb9-2"></a></span>
<span id="cb9-3"><a href="#cb9-3"></a></span>
<span id="cb9-4"><a href="#cb9-4"></a><span class="kw">qplot</span>(ang,normF.fat)<span class="op">+</span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x=</span>ang[<span class="kw">which.max</span>(normF.fat)],<span class="dt">y=</span>normF.fat[<span class="kw">which.max</span>(normF.fat)]),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">size=</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="mod8_proj_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>ang[<span class="kw">which.max</span>(normF.fat)] <span class="co">#Find angle for Fmax for fatigue data</span></span></code></pre></div>
<pre><code>## [1] 123.75</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>poly.m2.fat &lt;-<span class="st"> </span><span class="kw">lm</span>(normF.fat<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">2</span>)) <span class="co">#second order</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>poly.m3.fat &lt;-<span class="st"> </span><span class="kw">lm</span>(normF.fat<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">3</span>)) <span class="co">#third order</span></span>
<span id="cb12-3"><a href="#cb12-3"></a>poly.m4.fat &lt;-<span class="st"> </span><span class="kw">lm</span>(normF.fat<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">4</span>)) <span class="co">#fourth order</span></span>
<span id="cb12-4"><a href="#cb12-4"></a></span>
<span id="cb12-5"><a href="#cb12-5"></a><span class="kw">AICc</span>(poly.m2.fat,poly.m3.fat,poly.m4.fat) <span class="co">#the second order model fits best</span></span></code></pre></div>
<pre><code>##             df      AICc
## poly.m2.fat  4 -54.91075
## poly.m3.fat  5 -55.05750
## poly.m4.fat  6 -49.10034</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>normF.pred.fat &lt;-<span class="st"> </span><span class="kw">predict</span>(poly.m2.fat,<span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">ang=</span>x.pred)) <span class="co">#predict the force using 1000 angles</span></span>
<span id="cb14-2"><a href="#cb14-2"></a></span>
<span id="cb14-3"><a href="#cb14-3"></a><span class="kw">qplot</span>(ang,normF)<span class="op">+</span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x.pred,<span class="dt">y=</span>normF.pred.fat),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)<span class="op">+</span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x.pred[<span class="kw">which.max</span>(normF.pred.fat)],<span class="dt">y=</span>normF.pred.fat[<span class="kw">which.max</span>(normF.pred.fat)]),<span class="dt">size=</span><span class="dv">5</span>,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="mod8_proj_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a>x.pred[<span class="kw">which.max</span>(normF.pred.fat)]<span class="op">-</span>x.pred[<span class="kw">which.max</span>(normF.pred)] <span class="co">#shift in angle for Fmax, theta_max</span></span></code></pre></div>
<pre><code>## [1] 10.24775</code></pre>
<p>Looks as if there’s a 10.3<span class="math inline">\(^o\)</span> shift in <span class="math inline">\(\theta_{max}\)</span>.</p>
<p>Say we had a bunch of data (from only 10 subjects) and you wanted to compare the control against fatigued data graphically, you could do the following. First we’ll simulate some control and fatigue data, adding random noise drawn form a normal distribution and plot the data with a color according to experiment to quickly assess the pattern.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ tibble  3.1.5     ✓ dplyr   1.0.7
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   2.0.2     ✓ forcats 0.5.1
## ✓ purrr   0.3.4</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="kw">set.seed</span>(<span class="dv">1234</span>) <span class="co">#to keep random noise the same</span></span>
<span id="cb21-2"><a href="#cb21-2"></a></span>
<span id="cb21-3"><a href="#cb21-3"></a>sub &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span> <span class="co">#ten subjects</span></span>
<span id="cb21-4"><a href="#cb21-4"></a>dat.l &lt;-<span class="st"> </span><span class="kw">list</span>() <span class="co">#empty list</span></span>
<span id="cb21-5"><a href="#cb21-5"></a></span>
<span id="cb21-6"><a href="#cb21-6"></a><span class="co">#loop to run through subjects and simulate data based on noise added to data above</span></span>
<span id="cb21-7"><a href="#cb21-7"></a><span class="cf">for</span>(i <span class="cf">in</span> sub){</span>
<span id="cb21-8"><a href="#cb21-8"></a>  noise &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="kw">length</span>(ang),<span class="dt">mean =</span> <span class="fl">0.02</span>,<span class="dt">sd =</span> <span class="fl">0.01</span>)</span>
<span id="cb21-9"><a href="#cb21-9"></a>  noise2 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="kw">length</span>(ang),<span class="dt">mean =</span> <span class="fl">0.02</span>,<span class="dt">sd =</span> <span class="fl">0.01</span>)</span>
<span id="cb21-10"><a href="#cb21-10"></a>  dat.l[[i]] &lt;-<span class="st"> </span><span class="kw">tibble</span>(</span>
<span id="cb21-11"><a href="#cb21-11"></a>    <span class="kw">rbind</span>(</span>
<span id="cb21-12"><a href="#cb21-12"></a>      <span class="kw">data.frame</span>(ang,<span class="dt">force=</span>normF<span class="op">+</span>noise,<span class="dt">subject=</span>i,<span class="dt">exp=</span><span class="st">&quot;control&quot;</span>),</span>
<span id="cb21-13"><a href="#cb21-13"></a>      <span class="kw">data.frame</span>(ang,<span class="dt">force=</span>normF.fat<span class="op">+</span>noise2,<span class="dt">subject=</span>i,<span class="dt">exp=</span><span class="st">&quot;fatigue&quot;</span>)</span>
<span id="cb21-14"><a href="#cb21-14"></a>  )  </span>
<span id="cb21-15"><a href="#cb21-15"></a>  )<span class="op">%&gt;%</span></span>
<span id="cb21-16"><a href="#cb21-16"></a><span class="st">    </span><span class="kw">group_by</span>(subject,exp)<span class="op">%&gt;%</span></span>
<span id="cb21-17"><a href="#cb21-17"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">force=</span>force<span class="op">/</span><span class="kw">max</span>(force))</span>
<span id="cb21-18"><a href="#cb21-18"></a>  </span>
<span id="cb21-19"><a href="#cb21-19"></a>}</span>
<span id="cb21-20"><a href="#cb21-20"></a></span>
<span id="cb21-21"><a href="#cb21-21"></a>dat &lt;-<span class="st"> </span><span class="kw">do.call</span>(rbind,dat.l) <span class="co">#get data into one tibble</span></span>
<span id="cb21-22"><a href="#cb21-22"></a></span>
<span id="cb21-23"><a href="#cb21-23"></a>dat<span class="op">%&gt;%</span></span>
<span id="cb21-24"><a href="#cb21-24"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(ang,force,<span class="dt">col=</span>exp))<span class="op">+</span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="mod8_proj_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Now let’s take our data and get AICc scores for our three polynomial models. We’ll group the data by subject and experiment and retrieve AICc from each model (<code>m2</code>, <code>m3</code>, and <code>m4</code>). Then, we’ll pivot the tibble to a longer format so that we have a single column for AICc values.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>AICs &lt;-<span class="st"> </span>dat<span class="op">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="st">  </span><span class="kw">group_by</span>(subject,exp)<span class="op">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3"></a><span class="st">  </span><span class="kw">summarize</span>(</span>
<span id="cb22-4"><a href="#cb22-4"></a>    <span class="dt">m2=</span><span class="kw">AICc</span>(<span class="kw">lm</span>(force<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">2</span>))), <span class="co">#second order</span></span>
<span id="cb22-5"><a href="#cb22-5"></a>    <span class="dt">m3=</span><span class="kw">AICc</span>(<span class="kw">lm</span>(force<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">3</span>))), <span class="co">#third order</span></span>
<span id="cb22-6"><a href="#cb22-6"></a>    <span class="dt">m4=</span><span class="kw">AICc</span>(<span class="kw">lm</span>(force<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">4</span>))) <span class="co">#fourth order</span></span>
<span id="cb22-7"><a href="#cb22-7"></a>  )<span class="op">%&gt;%</span></span>
<span id="cb22-8"><a href="#cb22-8"></a><span class="st">  </span><span class="kw">pivot_longer</span>(m2<span class="op">:</span>m4,<span class="dt">names_to=</span><span class="st">&quot;model&quot;</span>,<span class="dt">values_to=</span><span class="st">&quot;AICc&quot;</span>)<span class="op">%&gt;%</span></span>
<span id="cb22-9"><a href="#cb22-9"></a><span class="st">  </span><span class="kw">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 60 × 4
## # Groups:   subject [10]
##    subject exp     model  AICc
##      &lt;int&gt; &lt;chr&gt;   &lt;chr&gt; &lt;dbl&gt;
##  1       1 control m2    -43.2
##  2       1 control m3    -39.3
##  3       1 control m4    -42.5
##  4       1 fatigue m2    -49.3
##  5       1 fatigue m3    -46.0
##  6       1 fatigue m4    -37.7
##  7       2 control m2    -43.8
##  8       2 control m3    -39.4
##  9       2 control m4    -55.2
## 10       2 fatigue m2    -57.6
## # … with 50 more rows</code></pre>
<p>Now we’ll do something very similar, predicting values for 1000 discrete angles across our range of elbow positions. Notice that we’ve summarized the data by subject, experiment and model to find the angle (<code>x.pred</code>) which matches the max force value.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>fits &lt;-<span class="st"> </span>dat<span class="op">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2"></a><span class="st">  </span><span class="kw">group_by</span>(subject,exp)<span class="op">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3"></a><span class="st">  </span><span class="kw">summarize</span>(</span>
<span id="cb24-4"><a href="#cb24-4"></a>    <span class="dt">m2=</span><span class="kw">predict</span>(<span class="kw">lm</span>(force<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">2</span>)),<span class="dt">newdata=</span><span class="kw">data.frame</span>(<span class="dt">ang=</span>x.pred)), <span class="co">#second order</span></span>
<span id="cb24-5"><a href="#cb24-5"></a>    <span class="dt">m3=</span><span class="kw">predict</span>(<span class="kw">lm</span>(force<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">3</span>)),<span class="dt">newdata=</span><span class="kw">data.frame</span>(<span class="dt">ang=</span>x.pred)), <span class="co">#third order</span></span>
<span id="cb24-6"><a href="#cb24-6"></a>    <span class="dt">m4=</span><span class="kw">predict</span>(<span class="kw">lm</span>(force<span class="op">~</span><span class="kw">poly</span>(ang,<span class="dv">4</span>)),<span class="dt">newdata=</span><span class="kw">data.frame</span>(<span class="dt">ang=</span>x.pred)) <span class="co">#fourth order</span></span>
<span id="cb24-7"><a href="#cb24-7"></a>  )<span class="op">%&gt;%</span></span>
<span id="cb24-8"><a href="#cb24-8"></a><span class="st">   </span><span class="kw">pivot_longer</span>(m2<span class="op">:</span>m4,<span class="dt">names_to=</span><span class="st">&quot;model&quot;</span>)<span class="op">%&gt;%</span></span>
<span id="cb24-9"><a href="#cb24-9"></a><span class="st">   </span><span class="kw">group_by</span>(subject,exp,model)<span class="op">%&gt;%</span></span>
<span id="cb24-10"><a href="#cb24-10"></a><span class="st">   </span><span class="kw">summarize</span>(<span class="dt">theta_max=</span>x.pred[<span class="kw">which.max</span>(value)])<span class="op">%&gt;%</span></span>
<span id="cb24-11"><a href="#cb24-11"></a><span class="st">   </span><span class="kw">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 60 × 4
## # Groups:   subject, exp [20]
##    subject exp     model theta_max
##      &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;
##  1       1 control m2         107.
##  2       1 control m3         103.
##  3       1 control m4         104.
##  4       1 fatigue m2         115.
##  5       1 fatigue m3         118.
##  6       1 fatigue m4         117.
##  7       2 control m2         107.
##  8       2 control m3         103.
##  9       2 control m4         105.
## 10       2 fatigue m2         115.
## # … with 50 more rows</code></pre>
<p>Now let’s join these the <code>AICs</code> and <code>fits</code> tables so that we can filter the model predictions by which model fits best. Note <code>filter(best==TRUE)</code> after constructing a <code>best</code> column according to the minimum AICc score using <code>mutate()</code>.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a>best.models &lt;-<span class="st"> </span>fits<span class="op">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="st">  </span><span class="kw">left_join</span>(AICs)<span class="op">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="st">  </span><span class="kw">group_by</span>(subject,exp)<span class="op">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">best=</span>AICc<span class="op">==</span><span class="kw">min</span>(AICc))<span class="op">%&gt;%</span></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="st">  </span><span class="kw">filter</span>(best<span class="op">==</span><span class="ot">TRUE</span>)<span class="op">%&gt;%</span></span>
<span id="cb26-6"><a href="#cb26-6"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>best)<span class="op">%&gt;%</span></span>
<span id="cb26-7"><a href="#cb26-7"></a><span class="st">  </span><span class="kw">print</span>()</span></code></pre></div>
<pre><code>## Joining, by = c(&quot;subject&quot;, &quot;exp&quot;, &quot;model&quot;)</code></pre>
<pre><code>## # A tibble: 20 × 5
## # Groups:   subject, exp [20]
##    subject exp     model theta_max  AICc
##      &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;
##  1       1 control m2         107. -43.2
##  2       1 fatigue m2         115. -49.3
##  3       2 control m4         105. -55.2
##  4       2 fatigue m2         115. -57.6
##  5       3 control m4         107. -47.7
##  6       3 fatigue m3         119. -57.2
##  7       4 control m4         104. -55.4
##  8       4 fatigue m3         120. -51.9
##  9       5 control m4         103. -48.9
## 10       5 fatigue m2         115. -51.3
## 11       6 control m4         103. -41.7
## 12       6 fatigue m3         120. -53.7
## 13       7 control m4         104. -48.0
## 14       7 fatigue m3         120. -55.9
## 15       8 control m2         107. -48.5
## 16       8 fatigue m3         116. -65.9
## 17       9 control m4         103. -48.3
## 18       9 fatigue m2         115. -52.3
## 19      10 control m4         105. -49.3
## 20      10 fatigue m2         115. -55.0</code></pre>
<p>To investigate whether a shift if <span class="math inline">\(\theta_{max}\)</span> is different between the control and fatigue experiments, we can run the following ANOVA.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="kw">anova</span>(<span class="kw">lm</span>(theta_max<span class="op">~</span>exp,best.models))</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: theta_max
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## exp        1 749.21  749.21  180.18 8.144e-11 ***
## Residuals 18  74.85    4.16                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Lastly, we should calculate the mean shift with SEM. To find the shift, we can pivot the <code>best.models</code> tibble to a wider format so we can have <span class="math inline">\(\theta_{max}\)</span> for each experiment in separate columns and find the difference with <code>mutate()</code>. Then, <code>summarise()</code> can be used to find the mean and SEM.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a>best.models<span class="op">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">id_cols=</span>subject,<span class="dt">names_from =</span> exp,<span class="dt">values_from=</span>theta_max)<span class="op">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">shift=</span>fatigue<span class="op">-</span>control)<span class="op">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4"></a><span class="st">  </span><span class="kw">ungroup</span>()<span class="op">%&gt;%</span></span>
<span id="cb31-5"><a href="#cb31-5"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean.shift=</span><span class="kw">mean</span>(shift),<span class="dt">se.shift=</span><span class="kw">sd</span>(shift)<span class="op">/</span><span class="kw">sqrt</span>(<span class="kw">length</span>(shift)))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   mean.shift se.shift
##        &lt;dbl&gt;    &lt;dbl&gt;
## 1       12.2    0.960</code></pre>
</div>
</div>
<div id="project-report" class="section level1">
<h1>Project Report</h1>
<p>Please submit your report to your team GitHub repository as an .Rmd document with HTML output that addresses the following questions:</p>
<ul>
<li>Do class-wide force-angle data for isometric MVC accord to a typical FL relationship both under control and fatigued conditions?</li>
<li>Is there a significant shift between <span class="math inline">\(\theta_{max}\)</span> between the control and fatigue FL relationships?</li>
</ul>
<p>In answering these questions, be sure to use the visualization, modeling, and model-assessments tools we’ve used in the course so far.</p>
<p>The answers and narrative in your .Rmd should include the following components:</p>
<ul>
<li>A YAML header that specifies HTML output, the authors, and a bibliography named “BIOL3140.bib”. <strong>Submit this bibliography as well!</strong></li>
<li>Sections including an introduction, methods, results, discussion, author contributions, and references. Make sure that each, aside from the references, includes one to two short paragraphs. Specifically:
<ul>
<li>Introduction: Frame the questions, indicating why they are important, what background work has been done in this realm, and how you will answer them. <strong>Please include at least one reference to support the summary of previous work.</strong> Note: this can be done easily by refiguring the introduction to this project report.</li>
<li>Methods: Explicitly state how you answered the questions, including a narrative of all the analyses both qualitative and quantitative.</li>
<li>Results: Include any appropriate figures or tables and a narrative of the main results that are important to answering the questions.</li>
<li>Discussion: Succinctly declare how the results relate to the question and how they compare to previous work devoted to the topic. In addition, be sure to comment on the importance of your findings to the broader topic at hand. <strong>Please include at least one reference to another relevant study.</strong> Note: circling back to the introductions, both to this project description and yours, will be helpful here.</li>
<li>Author contributions: Briefly outline what each team member contributed to the project.</li>
</ul></li>
</ul>
<p>Project reports should be uploaded by 11:59 PM on Sunday, November 14th.</p>
<div class="green">
<div class="row">
<div class="col-sm-2">
<a class="far fa-sticky-note fa-5x" style="color:#939681"></a> <!-- regular style -->
</div>
<div class="col-sm-9">
<p>Please have a look at out <a href="phaseII_rubric.html">Phase II report rubric</a> to get a sense of how this and other Phase II reports will be grade.</p>
</div>
</div>
</div>
<p><br></p>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-rassier1999length">
<p>Rassier, DE, BR MacIntosh, and W Herzog. 1999. “Length Dependence of Active Force Production in Skeletal Muscle.” <em>Journal of Applied Physiology</em> 86 (5): 1445–57.</p>
</div>
<div id="ref-yeung2008shift">
<p>Yeung, SS, and EW Yeung. 2008. “Shift of Peak Torque Angle After Eccentric Exercise.” <em>International Journal of Sports Medicine</em> 29 (03): 251–56.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
