---
title: "Phase III Project Report Rubric"
---

# General Guidelines

Phase III is devoted to a single independent project that uses the data analysis and prototyping skills we've learned and refined in the first two phases of the course. Your team should work with Prof. K to develop an interesting question with a reasonable scope to answer with your Phase II project. Just like in Phase II, the project report for Phase III should resemble a short manuscript that models a scientific paper. By this, we mean that it should contain [appropriate headings or sections](mod4_proj.html#Headers) framing the question, how it was answered, the results, and how these results relate to the question and similar work that has been done. The following rubric represents how the 100 points for Phase III report will be assessed.

# Rubric
 |Component| **Spot On** |  **Pretty Good** | **Needs Work**  
|--------|-------- |-------- |--------
| Tasks and Outputs | Completes all tasks fully; submits all required outputs and materials on time, including those scheduled before the final deadline. <br>**(15 pts)** | Completes a majority but not all tasks fully; final submission meets the deadline but some preliminary deadlines may have been missed  <br>**( 8 pts)** | Completes few required tasks or submits few required materials; most submissions miss their respective deadlines <br>**(3 pts)**
| Scientific Rigor| The project approaches an important question in organismal biology with a reasonable scope using tools and techniques used in the course <br>**(15 pts)** | The project question is well defined, but perhaps trivial, or the project scope is too narrow or ambitious <br>**(8 pts)** | The question is trivial and the scope unreasonable. <br>**(3 pts)**
| Effort and Engagement | The individual or team pursues help from the instructor, ask  questions and/or seeks help regularly <br>**(15 pts)**|  Individual or team asks questions or seek help sometimes, but not regularly <br>**(8 pts)**  |  Individual or team does not seem help <br>**(3 pts)**
| Report Format | Report contains all the [appropriate headings and components](mod4_proj.html#Headers) (including a bibliography) <br>**(10 pts)**|  Report contains most of the appropriate headings and components (including a bibliography) <br>**(6 pts)** |  Report contains few of the appropriate headings and components <br>**(2 pt)**
| Analysis and Code | Report contains concisely written code chunks within the results or methods sections that produce creative analyses, figures, and/or tables that have clear implications for the project's question <br>**(15 pts)**|  One or a few code chunks are unneeded or produce analyses, figures, and/or tables that do not have clear implication for to the project goals <br>**(8 pts)**| No code chunks contained in report or all code chunks are unneeded or produce analyses, figures, and/or tables not directly related to the project goals <br>**(3 pts)** 
| Graphics and Tables | Figures, tables, and images are clear, add much to the results in analysis, and have concise but descriptive captions <br>**(10 pts)**|   One or a few figures, tables, and images are unneeded or inappropriate or they lack captions that are concise or descriptive  <br>**(6 pts)**|  All few figures, tables, and images are unneeded or inappropriate <br>**(2 pt)**
| Writing and Style | The writing is concise, clear, avoids passive constructions, and is in the past tense; grammar is appropriate <br>**(10 pts)**|   The writing is unclear or rambling in spots or uses passive constructions and future tense; grammar is shaky in spots <br>**(6 pts)** |   The writing is unclear, and/or uses passive constructions or future tense throughout; grammar is shaky for the most part <br>**(2 pt)**
| Sources and References | The report contains 3 references to primary research pieces that support statements of fact; references are contained in a [BibTex bibliography and inserted with `@` tags](mod4_proj.html#Inserting_References)  <br>**(10 pts)**| Report contains fewer than 3 references; some statements of scientific findings and fact are not supported by references; some references are not contained in a BibTex bibliography or inserted with `@` tags <br>**(6 pts)** |   Most statements of scientific findings and fact are not supported by references; references are not contained in a BibTex bibliography nor inserted with `@` tags <br>**(2 pt)**
||||
