---
title: "Project 5"
author: "Masen Palmerino, Betsy Kelly, Leanna Knight"
date: "2024-10-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(geomorph)
library(abind)
library(phytools)
library(parallel)
```

## Introduction

## Methods

## Results

```{r data, include=FALSE}
shark_dat <- read_csv("shark_data.csv")

f <- list.files("shark_points",full.names = T,pattern=".csv")

xy <- read_csv(f,id="file") %>% 
  select(file,X,Y) %>% 
  mutate(Y=abs(Y-max(Y))) %>% 
  mutate(file_name=gsub("*_.csv","",basename(file))) %>% 
  left_join(shark_dat) 

ldk_l <- list()

shark_sp <- xy$sp %>% unique

for(i in shark_sp){
  ldk_l[[i]] <- xy %>% 
    filter(sp==i) %>% 
    select(X,Y) %>% 
    data.frame
}

ldk <-  abind(ldk_l, along=3)

dimnames(ldk)[[3]] <-names(ldk_l)
```

```{r gpa, include=FALSE}
ldk_al <- gpagen(ldk)
```

```{r morphospace, echo=FALSE}
pca <- gm.prcomp(ldk_al$coords)

PCA <- pca$x %>% 
  data.frame %>% 
  select(Comp1:Comp4) %>% 
  mutate(sp=rownames(pca$x)) %>% 
  left_join(shark_dat)

PCA %>% 
  ggplot(aes(Comp1,Comp2,col=habitat))+geom_point()
```

```{r disparity, echo=FALSE}
gdf <- geomorph.data.frame(ldk_al,habitat=PCA$habitat)

md <- morphol.disparity(coords ~ 1, groups= ~ habitat, data = gdf, iter = 10000, print.progress = FALSE)

summary(md)
```

```{r evolution, echo=FALSE}
phy <- readNexus("shark_trees.nex")
length(phy)

phy2 <- keep.tip(phy,PCA$sp)

gp_hab <- PCA$habitat
names(gp_hab) <- PCA$sp

saveRDS(list(hab=gp_hab,ldk=ldk_al$coords),"er_dat.RDS")
```

```{r parallel, echo=FALSE}
er_fun <- function(x) {
  dat <- readRDS("er_dat.RDS")
  library(geomorph)
    er <- compare.evol.rates(A = dat$ldk,
        phy = x, method = "simulation", gp = dat$hab)
}

cl <- makeCluster(getOption("cl.cores", 2))
er <- parLapply(cl,phy2,er_fun)
stopCluster(cl)

print(er)
```
## Discussion

## Author Contributions 

## References


