---
title: "Schedule"
---

<style>
div.green { background-color:#c7d1c0; border-radius: 5px; padding: 20px;}
</style>



# Phase I: The Basics

In this phase, we'll learn the basics of instrumentation and data analysis by working through 5 learning modules devoted to instrument design and data analysis. This will most likely be the most challenging part of the course in that many, if not most of you will not have ever designed and built instruments and data acquisition systems, let alone analyzed data from them. Rest assured, your experience will be curated, sticking to the bare bones of instrument design and data science. This introductory phase will set the groundwork for Phase II, the independent development of sensors and data analysis.

## Module 1: Data Pirates Code with. . . . R, Introduction to the Basics

In this module we'll tackle where to find resource you'll need on a week-to-week, module-by-module basis. In addition, we'll work on the first important topic of the course: an introduction to R, an ever more popular language for data analysis and visualization. We'll focus on the basics of importing and tidying data in R. By importing, we mean loading data collected by scientists and stored in text files, the lingua franca of scientific data. By tidying, we mean preparing data for analysis.

### Dates 
Weeks 1 & 2 (Aug 28—Sep 10):

### Key Concepts
  + Course workflow
  + Course expectations
  + R user interface
  + Working directory
  + Objects, functions, arguments, and scripts in R
  + Lists, data frames, and matrices
  + Basic R notation
  + The `for` loop
  + git, github, and version control
  
### Learning Objectives

Upon completion of this week and module, students will be able to:

  + Know what is expected during Phase I of the course
  + Open R and RStudio
  + Set a working directory and load data in R
  + Recognize the difference between different objects (e.g., vectors, lists, data frames etc.)
  + Perform simple data operations and manipulation of data objects in R
  + Construct and run a `for` loop in R to automate a interatively redundant task.
  + clone a local directory and version controlteam-based work on common script and report files
 
### Read/Watch 

From [Hands on Programming with R](https://rstudio-education.github.io/hopr) (HOPR)

  + [Appendices A—D](https://rstudio-education.github.io/hopr/starting.html) 
  + [Part I](https://rstudio-education.github.io/hopr/project-1-weighted-dice.html)
  + [Part II](https://rstudio-education.github.io/hopr/project-2-playing-cards.html)
  + [Chapter 5: R Objects](https://rstudio-education.github.io/hopr/r-objects.html)
  + [Chapter 6: R Notation](https://rstudio-education.github.io/hopr/r-notation.html)
  + [Chapter 7: Modifying Values](https://rstudio-education.github.io/hopr/modify.html)
  + [Chapter 11.3: For Loops](https://rstudio-education.github.io/hopr/loops.html#for-loops)
 
When reading through HOPR, make sure to have R and R Studio up and running so that you can copy and paste code from HOPR into an R file and run the specified commands and complete the books project tasks. This will help tremendously in getting the hang of things.

From [Happy Git with R](https://happygitwithr.com)

  + [Chapter 12](https://happygitwithr.com/rstudio-git-github.html)


Be sure you're familiar with the [prerequsites](https://happygitwithr.com/rstudio-git-github.html#prerequisites) outlined in Chapter 12. We'll cover git and github in class on August 30st. Just introduce yourself to the concepts.

Check out the new [github access token requirements](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token).

 

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">

<div class = "green">
<div class="row">
  <div class="col-sm-2"><a class="far fa-sticky-note fa-5x" style="color:#939681"></a> <!-- regular style --></div>
  <div class="col-sm-9">This is a lot of reading and fiddling with R. Don't worry too much about understanding every detail! The goal here is to just get the hang of things and, just as importantly, know where to find answers to questions about how R works.</div>
</div>
</div>

<br>

### Do

  + Post one and respond to one question each week of Module 1 in our [discussion board](https://github.com/orgs/bcorgbio/teams/biol-3140) 
  + [Install R and RStudio](https://rstudio-education.github.io/hopr/starting.html#starting)
  + Clone a github team repository to a local directory (done in class with Prof. K's help on Wednesday, Aug 30)
  + Complete and commit a report for Module 1 Project 


### Guiding Questions
  
  + How do I perform simple operations in R?
  + What are R's basic object classes?
  + How does external data get loaded into R?
  + How does one subset common data objects in R?
  + How does a `for` loop work and when should it be used?
  + What are the basic git opertations and their value in sharing code.
  
### Module 1 Schedule

All assignments are due at 11:59 on the specified date.

 || Monday <br> 8/28 |  Tuesday <br>8/29    | Wednesday<br>  8/30 | Thursday <br> 8/31 | Friday <br> 9/1 |Saturday<br> 9/2 | Sunday<br> 9/3
|--------|-------- |--------|-------- |--------|--------|--------|--------    
**Assignment due** |[slides](lect\3140_f23_8-28.html) | | [slides](lect\3140_f23_8-30.html) <br> Post question to discussion board | Answer a question on discussion board  | | |

 || Monday <br> 9/4 |  Tuesday <br>9/5    | Wednesday<br>  9/6 | Thursday <br> 9/7 | Friday <br> 9/8 |Saturday<br> 9/9 | Sunday<br> 9/10
|--------|-------- |--------|-------- |--------|--------|--------|--------    
**Assignment due** | | | Post question to discussion board  <br> <br> [WCR 1](WCRs/WCR_1.html)| | Answer a question on discussion board | | commit Module 1 project report
 |||||||
<br>

## Module 2: Data Wrangling: Introduction to Tools of the Trade in Data Analysis

This module is intended to give students the background and skills to begin simple data tidying and transformation operations. We need our data to be tidy before we can analyze it, that is, structured in a way that makes analysis possible. In addition, often the data we have aren't exactly what we want to analyze. In this module, we'll focus on how to read, tidy, and merge data.

### Dates: 
Week 3 (Sep 11—17): 

### Key Concepts
  + Reading text files in R
  + Adding data based on data (i.e., data transformation)
  + Summarize data according to variables
  + Tidying data in R
  + Relational data and merging data sets

### Learning Objectives

Upon completion of this week and module, students will be able to:

  + Read text data into R.
  + Pivot data from wide to longer formats and vice versa.
  + Add columns of data to a data set based on values in other columns.
  + Write and use a simple function in R.
  + Tidy a data set to begin analysis with a particular goal in mind.
  + Join data sets based on similar data (i.e., key) attributes
  

### Read/Watch
All form [R for Data Science](https://r4ds.had.co.nz/wrangle-intro.html) (R4DS):

  + [Chapter 5: Transformations](https://r4ds.had.co.nz/transform.html)

  + All from the [Wrangle Section](https://r4ds.had.co.nz) of R4DS:
    + [Chapter 9: Introduction](https://r4ds.had.co.nz/wrangle-intro.html)
    + [Chapter 10: Tibbles](https://r4ds.had.co.nz/tibbles.html)
    + [Chapter 11: Data Import](https://r4ds.had.co.nz/data-import.html) [don't worry too much about 11.3 and 11.4 "Parsing Vectors" and "Parsing Files] 
    + [Chapter 12: Tidy Data](https://r4ds.had.co.nz/tidy-data.html)
    + [Chapter 13: Relational Data](https://r4ds.had.co.nz/relational-data.html) 

  + [Chapter 19.1: Functions](https://r4ds.had.co.nz/functions.html)    
    
<br>


<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"> 

<div class = "green">
<div class="row">
<div class="col-sm-2"><a class="far fa-sticky-note fa-5x" style="color:#939681"></a> <!-- regular style --></div>
<div class="col-sm-9"> As with HOPR, make sure to have R and R Studio up and running so that you can copy and paste code from R4DS into an R file and run the specified commands and complete the book's exercises.</div>
</div>
</div> 
<br>

### Do 

  + Post one and respond to one question in [discussion board](https://github.com/orgs/bcorgbio/teams/biol-3140) [10 points]
  + Complete and commit a report for Module 2 Project 


### Guiding Questions

  + How does one read data into R? 
  + What is tidy data? 
  + What's the difference between long and wide data tables? 
  + How does one add and summarize data in R?
  + How does one merge data in join operations?  
<br>

### Module 2 Schedule

All assignments are due at 11:59 on the specified date. 

  || Monday <br> 9/11 |  Tuesday <br>9/11 | Wednesday<br>  9/13 | Thursday <br> 9/14 | Friday <br> 9/15 |Saturday<br> 9/16 | Sunday<br> 9/17
  |--------|-------- |--------|-------- |--------|--------|--------|--------
  **Assignment due** |<br> <br> [slides](lect\3140_f23_9-11.html)  | | Post question to discussion board <br> <br> [WCR 2](WCRs/WCR_2.html)| Answer a question on discussion board  | | | commit Module 2 Project Report
  ||||||||


## Module 3: The Whiz and Viz Bang of Data: The Basics of Data Visualization and Modeling

In Module 3, we'll cover the basics of visualizing and modeling data and hypothesis testing. We've used some simple visualization techniques in `ggplot` already and we'll leverage this introduction to dig deeper into how data can be plotted to explore and ask informed questions about it. In addition, we'll learn how and when to compared the fit of models.

### Dates: 

Week 4 (Sep 18—24):

### Key Concepts
  + The grammar of `ggplot`
  + Linear models and least squares regression
  + Phylogenetic signal and correction
  + Brownian motion models of trait evolution
  + Model fit and the Aikiake Information Criterion (AIC)

### Learning Objectives

Upon completion of this week and module, students will be able to:

  + Perform simple modeling operations in R.
  + Explore patterns to construct these models by visualizing data in R's `ggplot` environment.
  + Perform phylogenetically corrected regression analysis of comparative data.
  + Compare model fit using an information theory approach.
  
### Read/Watch

All form [R for Data Science](https://r4ds.had.co.nz/wrangle-intro.html) (R4DS):

  + Chapter 3:[Data Visualiation](https://r4ds.had.co.nz/data-visualisation.html)
  + Section IV: Models
  
    * Chapter 22: [Introduction](https://r4ds.had.co.nz/model-intro.html)
    * Chapter 23: [Model Basics](https://r4ds.had.co.nz/model-basics.html)
    * Chapter 24: [Model Building](https://r4ds.had.co.nz/model-building.html)
    
From [Phylogenetic Comparative Methods](https://lukejharmon.github.io/pcm) by Luke Harmon [don't worry too much about the mathematics, focus on the definitions and concepts]
  
  + Chapter 1.2:[The Roots of Comparative Methods](https://lukejharmon.github.io/pcm/chapter1_introduction/#section-1.2-the-roots-of-comparative-methods)
  + Chapter 2.1-2.3: [Fitting Statistical Models to Data](https://lukejharmon.github.io/pcm/chapter2_stats/)
  + Chapter 3.1-3.4:[Introduction to Brownian Motion](https://lukejharmon.github.io/pcm/chapter3_bmintro/#chapter-3-introduction-to-brownian-motion)
  + Chapter 6.4: [Non-Brownian evolution under stabilizing selection](https://lukejharmon.github.io/pcm/chapter6_beyondbm/#section-6.4-non-brownian-evolution-under-stabilizing-selection)


### Do 

  + Post one and respond to one question in [discussion board](https://github.com/orgs/bcorgbio/teams/biol-3140) [10 points]
  + Complete and commit a report for Module 3 Project 


### Guiding Questions

+ What are the basic components of plotting in `ggplot`?
+ How does one use basic visualization techniques to propose questions in biology?
+ How does one construct simple models in R? 
+ How does one account for phylogeny when constructing models of comparative data?
+ What basic models of trait evolution can one use in comparative research?
+ How does one know if they're asking the right question (i.e., using the right model) in comparative research?

<br>

### Module 3 Schedule

All assignments are due at 11:59 on the specified date. 

  || Monday <br> 9/18 |  Tuesday <br>9/19    | Wednesday<br>  9/20 | Thursday <br> 9/21 | Friday <br> 9/22 |Saturday<br> 9/23 | Sunday<br> 9/24
  |--------|-------- |--------|-------- |--------|--------|--------|--------
  **Assignment due** | <br> <br> [slides](lect\3140_f23_9-23.html) | | Post question to discussion board <br> <br> [WCR 3](WCRs/WCR_3.html)** | <br> <br> [slides](lect\3140_f23_9-23.html)| Answer a question on discussion board  | | | commit Module 3 Project Report
  ||||||||
  
  
## Module 4: Making Messes Pretty: Leveraging Markdown to Produce Pleasing Reports

In Module 4, we'll cover the basics of authoring reports in R Markdown, a markup language used to communicate the results of analysis in R. With R Markdown, you'll develop a framework for compiling ideas, code, and graphics in one reproducible document.

### Dates: 

Week 5 (Sep 25—Oct 1):

### Key Concepts
  + The R Markdown framework
  + Text markup
  + Code chunks
  + Graphics and tables in R Markdown 
  + Knitting documents in R Markdown

### Learning Objectives

Upon completion of this week and module, students will be able to:

  + Author a simple R Markdown.
  + Run code within an R Markdown document.
  + Add graphics (i.e., figures), images, tables and references to and R Markdown document. 
  + Render (i.e., knit) this R Markdown into HTML and PDF documents.
  
### Read/Watch

  + Chapter 27 in R4DS:[R Markdown](https://r4ds.had.co.nz/r-markdown.html)
  + [R Studio's markdown tutorial](https://rmarkdown.rstudio.com/)
    

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"> 

<div class = "green">
<div class="row">
<div class="col-sm-2"><a class="far fa-sticky-note fa-5x" style="color:#939681"></a> <!-- regular style --></div>
<div class="col-sm-9"> 
This module is very much learn as you go. Please dive right into the project and come back to the readings when clarifications are needed. 
</div>
</div>
</div> 
<br>

### Do 

  + Post one and respond to one question in [discussion board](https://github.com/orgs/bcorgbio/teams/biol-3140) [10 points]
  + Complete and commit a report for Module 3 Project 


### Guiding Questions

+ What are the basic components of an .Rmd?
+ How does one included headers, marked up text, graphics, tables, and references in an .Rmd?
+ How does one render and .Rmd into an HTML document? 

<br>

### Module 4 Schedule

All assignments are due at 11:59 on the specified date. 

  || Monday <br> 9/25 |  Tuesday <br>9/26    | Wednesday<br>  9/27 | Thursday <br> 9/28 | Friday <br> 9/29 |Saturday<br> 9/30 | Sunday<br> 10/1
  |--------|-------- |--------|-------- |--------|--------|--------|--------
  **Assignment due** | [slides](lect\3140_f23_9-25.html) <br> <br> | | Post question to discussion board  <br> <br> [WCR 4](WCRs/WCR_4.html)| Answer a question on discussion board  | | | commit Module 4 Project Report
  ||||||||

## Module 5: Cheap Tricks in Physiology: Designing and Programming Simple, Low-Cost Data Acquisition Systems

This module is intended to give students the background and skills to begin designing and programming of simple hardware devices using Arduino.


### Dates 
Week 6 (Oct 2—8):

### Key Concepts
  + Arduino IDE basics (the sketch).
  + Instrument design basics.
  + Saving data output from the serial monitor.
  
### Learning Objectives

Upon completion of this week and module, students will be able to:

  + Design and program a simple temperature Arduino DAQ.
  + Output data from a DAQ for subsequent analysis.

### Read/Watch 

  + [What is Arduino?](https://www.arduino.cc/en/Guide/Introduction)
  + [Getting started with Arduino](https://www.arduino.cc/en/Guide)
  + [What is Arduino IDE?](https://www.arduino.cc/en/Guide/Environment)
  + [Getting Started with the Arduino UNO](https://www.arduino.cc/en/Guide/ArduinoUno)
  + [The Serial Monitor](https://learn.adafruit.com/adafruit-arduino-lesson-5-the-serial-monitor/the-serial-monitor)
  + [How Does a Breadboard Work](https://www.sciencebuddies.org/science-fair-projects/references/how-to-use-a-breadboard)
  + [Using a DS18B20 sensor](https://randomnerdtutorials.com/guide-for-ds18b20-temperature-sensor-with-arduino/)


### Do

  + Post one and respond to one question in [discussion board](https://github.com/orgs/bcorgbio/teams/biol-3140)
  + [Install Arduino IDE](https://www.arduino.cc/en/Guide)
  + Work through "Blink" sketch in [Getting Started with the Arduino UNO](https://www.arduino.cc/en/Guide/ArduinoUno) (work with the desktop IDE)
  + Complete Module 5 Project


### Guiding Questions

  + What are the major components of an Arduino microcontroller?
  + What are the major components of an Arduino-based DAQ? 
  + How does one program an Arduino microcontroller?
  + How are data acquired from an Arduino unit?

### Module 5 Schedule

All assignments are due at 11:59 on the specified date.

 || Monday <br> 10/2 |  Tuesday <br>10/3    | Wednesday<br>  10/4 | Thursday <br> 10/5 | Friday <br> 10/6 |Saturday<br> 10/7 | Sunday<br> 10/8 
|--------|-------- |--------|-------- |--------|--------|--------|--------    
**Assignment due** |[slides](lect\3140_f23_10-2.html)| | Post question to discussion board <br> <br> [WCR 5](WCRs/WCR_5.html) | Answer a question on discussion board | | | commit Module 5 Project Report
  ||||||||




# Phase II: Developing a Toolbox

In Phase II, we'll use our new-found instrument- and code-development skills to address key questions in organismal biology. These will be self-guided explorations of instrument design and use and data analysis meant to challenge you to put these skills to good use in answering how vertebrates muscles work, phylogeny matters in physiological systems, and how a changing climate impacts the distribution of vertebrates. Within this phase we'll break up into our teams to focus on 4 modules, some data driven, the others both data and instrument driven.

## Module 6: The Shape of Pretty Things: Wing Shape Evolution in the Lepidoptera

This module puts our newly formed data analysis and markdown skills to use in answering how wing shape has evolved in the Lepidoptera (i.e., the moths and butterflies). Specifically, we'll test whether wing shape has evolved differently between the two major groups of this indect order.

### Dates:

Weeks 7--9 (Oct 9—27):

### Key Concepts
  <!-- + Saving instrument data to an SD card. -->
  + Morphometrics
  + Fluid mechanics
  + Evolutionary rate
  + Allometric scaling
  + Pagel's $\lambda$ and phylogenetic signal
  + Phylognetically informed regression
  
### Learning Objectives

Upon completion of this module, students will be able to:

  + Understand the basics of geometric and outline morphometrics.
  + Assemble a large dataset of comparative shape information.
  + Comment on how accounting for phylogenetic relationships affects analysis in shape studies.

### Read/Watch 

  <!-- + ~~[Temp sensor with SDcard module tutorial](http://arduinolearning.com/projects/temperature-logger.php)~~ -->
  <!-- + [Temp sensor with SDcard module tutorial](https://maker.pro/arduino/tutorial/how-to-make-an-arduino-sd-card-data-logger-for-temperature-sensor-data) -->
  
  + [DeVries, P.J., Penz, C.M. and Hill, R.I., 2010. Vertical distribution, flight behaviour and evolution of wing morphology in Morpho butterflies. Journal of Animal Ecology, 79(5): 1077-1085.](DeVries_etal_20210.pdf)
  + [Intoduction to Momocs](https://momx.github.io/Momocs/articles/Momocs_intro.html)

### Do

  + Post one and respond to one question in [discussion board](https://github.com/orgs/bcorgbio/teams/biol-3140)
  + Upload team data files to [this directory](https://drive.google.com/drive/folders/11VBPXKHWvlBSZ9z2asQ8EG4NYsGoOk0U?usp=sharing) by Tuesday, October 17th
  + Complete and commit Module 6 Project report


### Guiding Questions

  + How does one acquire shape information for comparative analysis?
  + Did shape evolve differently between the moths and butterflies?
  + How does one formulate a complete .Rmd report of Phase II of the course?

### Module 6 Schedule

All assignments are due at 11:59 on the specified date.


 || Monday <br> 10/9 |  Tuesday <br>10/10*    | Wednesday<br>  10/11 | Thursday <br> 10/12 | Friday <br> 10/13 |Saturday<br> 10/14 | Sunday<br> 10/15
 |--------|-------- |--------|-------- |--------|--------|--------|-------- 
**Assignment due** | | | Post question to discussion board <br> <br> [WCR 6](WCRs/WCR_6.html)| Answer a question on discussion board  | | |
 
 || Monday <br> 10/16 |  Tuesday <br>10/17    | Wednesday<br>  10/18 | Thursday <br> 10/19 | Friday <br> 10/20* |Saturday<br> 10/21 | Sunday<br> 10/22
 |--------|-------- |--------|-------- |--------|--------|--------|-------- 
 **Assignment due** | | | Post question to discussion board <br> <br> [WCR 7](WCRs/WCR_7.html)| Answer a question on discussion board <br> Upload team data files to [this directory](https://drive.google.com/drive/folders/11VBPXKHWvlBSZ9z2asQ8EG4NYsGoOk0U?usp=sharing) | | | 
 
  || Monday <br> 10/23 |  Tuesday <br>10/24    | Wednesday<br>  10/25 | Thursday <br> 10/26 | Friday <br> 10/27 |Saturday<br> 10/28 | Sunday<br> 10/29
 |--------|-------- |--------|-------- |--------|--------|--------|-------- 
 **Assignment due** | | | Post question to discussion board  <br> <br> [WCR 8](WCRs/WCR_8.html)| Answer a question on discussion board <br>  | | | Push 6 Project Report


*Note: 10/10 is a Monday schedule and there will be no class on 10/20.


## Module 7:  Beach Muscles: Exploring Force-Length Relationships in Vertebrate Muscle 

In this module, we'll explore how the force produced by vertebrate muscles is constrained by its length. To do this, we'll design an Arduino-based load sensing data-acquisition system to record force produced by upper-arm muscles over a series of different resting length. From our data, we'll establish models of forearm force-length properties and investigate how fatigure changes this imporant property of vertebrate muscle.

### Dates: 

Weeks 11 & 12 (Oct 30—Nov 12):

### Key Concepts
  + Cross-bridge theory
  + Isometric force
  + Maximum voluntary contractions (MVCc)
  + Force-length relationships
  + Mechanical advantage
  
### Learning Objectives

Upon completion of this week and module, students will be able to:

  + Construct and program a low-cost load-cell DAQ system.
  + Comment on the FL relationship in human skeletal muscles and the effect of fatigue on the shape of this relationship.

### Read/Watch 

  + Read [Rassier, D.E., MacIntosh, B.R. and Herzog, W., 1999. Length dependence of active force production in skeletal muscle. Journal of applied Physiology, 86(5), pp.1445-1457. 83–95.](https://journals.physiology.org/doi/full/10.1152/jappl.1999.86.5.1445)
  + Read [Oregon State's Body Physics page](https://openoregon.pressbooks.pub/bodyphysics/chapter/body-levers/)
  + Read [The Wheastone Bridge from Omega](https://www.omega.com/en-us/resources/wheatstone-bridge)
  

### Do
  + Post one and respond to one question in [discussion board](https://github.com/orgs/bcorgbio/teams/biol-3140)
  + Complete and commit Module 7 Project report
  + Upload force-angle data to [this directory](https://drive.google.com/drive/folders/17KPrL6-LNnpwaA6o7fOHIMLUjbY8mcnT?usp=sharing) by Sunday, November 12th



### Guiding Questions

  + How does one construct a low-cost load-cell force DAQ system?
  + Can angle-force measurements predict force-length (FL) relationships in the flexors of the human upper arm?
  + Does eccentric fatigue shift the FL relationship of human forearm flexors?
  
### Module 7 Schedule

All assignments are due at 11:59 on the specified date.

|| Monday <br> 11/6 |  Tuesday <br>11/7   | Wednesday<br>  11/8 | Thursday <br> 11/9 | Friday <br> 11/10 |Saturday<br> 11/11 | Sunday<br> 11/12
|--------|-------- |--------|-------- |--------|--------|--------|--------    
**Assignment due** | | | Post question to discussion board <br> <br> [WCR 9](WCRs/WCR_9.html)| Answer a question on discussion board | | |Upload team data files to [this directory](https://drive.google.com/drive/folders/17KPrL6-LNnpwaA6o7fOHIMLUjbY8mcnT?usp=sharing)

 || Monday <br> 11/13 |  Tuesday <br>11/14    | Wednesday<br>  11/15 | Thursday <br> 11/16 | Friday <br> 11/17 |Saturday<br> 11/18 | Sunday<br> 11/19
 |--------|-------- |--------|-------- |--------|--------|--------|-------- 
**Assignment due** | | | <br> <br> [WCR 10](WCRs/WCR_10.html) Post question to discussion board | Answer a question on discussion board  | | | Commit Module 8 Project Report
||||||||


## Module 8:   Birds of a Feather Migrate Together . . . Sometimes: Using EBird data to Explore the Phenology of Passerine Migration (data driven)

In this module, we'll explore the phenology of spring arrival timing for neotropical passerines as it relates to historical weather conditions. To do so, we'll download species occurrence data from the Global Biodiversity Information Facility (GBIF), an international network and data infrastructure whose goal is to provide users open access to data about all types of life on Earth. We'll access GBIF data using [`rgif`](https://www.gbif.org/tool/81747/rgbif), an R package that permits access to GBIF's application programming interface (API). An API permits a user to interact with multiple software pieces (databases, code sources for processing and analysis, etc.). To assemble historical weather data, we'll also use another R package, `rnoa`. This package contains functions that interact with [NOAA's National Climatic Data Center's API](https://www.ncdc.noaa.gov/cdo-web/webservices/v2).



### Dates 
Weeks 12 & 13 (Nov 20—Dec 8):

### Key Concepts

  + API
  + Phenology
  + Migrations
  + Linear Mixed-effects Modeling

### Learning Objectives

Upon completion of this week and module, students will be able to:

  + Download data using R's interface to one of several APIs.
  + Apply linear mixed-effect models to biological data.
  + Comment on how climatic and meteorological conditions may effect bird poulaiton.
  
### Read/Watch 

  + Watch [Matthew E. Clapham from UCSC on Linear Mixed-Effect Modles](https://www.youtube.com/watch?v=QCqF-2E86r0)
  + Read [Knudsen, Endre, Andreas Lindén, Christiaan Both, Niclas Jonzén, Francisco Pulido, Nicola Saino, William J Sutherland, et al. 2011. “Challenging Claims in the Study of Migratory Birds and Climate Change.” Biological Reviews 86 (4): 928–46](https://onlinelibrary.wiley.com/doi/pdf/10.1111/j.1469-185X.2011.00179.x?casa_token=K1xQ3N19mywAAAAA:QURRP-NVNPk8V6W444cY6C3BUe5Py0WppwbsHnzPQLLChgJMZCE-95YxVDxZHVzQH9rDUCjqk9ovmyJB)
  

### Do
  + Post one and respond to one question in [discussion board](https://github.com/orgs/bcorgbio/teams/biol-3140)
  + Complete and commit Module 9 Project report


### Guiding Questions

  + How does one download data using interfaces developed for R?
  + Is something other the temperature important in explaining the arrival time of neotropical migrants in MA?

  
### Module 8 Schedule

All assignments are due at 11:59 on the specified date.

 || Monday <br> 11/20 |  Tuesday <br>11/21    | Wednesday<br>  11/22 | Thursday <br> 11/23 | Friday <br> 11/24 |Saturday<br> 11/25 | Sunday<br> 11/26
 |--------|-------- |--------|-------- |--------|--------|--------|-------- 
**Assignment due** | | Post question to discussion board* <br> <br> [WCR 11](WCRs/WCR_11.html)| Answer a question on discussion board* | | | | 

 || Monday <br> 11/27 |  Tuesday <br>11/28    | Wednesday<br>  11/29 | Thursday <br> 11/30 | Friday <br> 12/1 |Saturday<br> 12/2 | Sunday<br> 12/3
 |--------|-------- |--------|-------- |--------|--------|--------|-------- 
**Assignment due** | | | Post question to discussion board <br> <br> [WCR 12](WCRs/WCR_12.html) | Answer a question on discussion board | | | Commit Module 8 Project Report
||||||||

*note shift due to Thanksgiving week


# Phase III: Final Projects

In Phase III, you'll be tasked with quickly developing a project of your own design that  either (1) requires the fabrication of a new or modified data acquisition system or (2) the acquisition of data from a peer-reviewed study or database. The goal of this project is to answer a question personal and interesting to your team. The question should be new within the context of the course and reflect a physiological focus (i.e., not ). This project will require you to first delve into the the scientific literature to set the stage and then leverage your new data-analysis and report-writing skills in the synthesis of 4-5 page markdown. This final project report should follow the same format and requirements of the reports produced in Phase II, but with expanded content. 

More details about the final project and its expectations can be found [here](final_proj.html).

  
## Final Project Schedule

### Dates 
Weeks 15 & beyond (Dec 4—Dec 13):

All assignments are due at 11:59 on the specified date.

|| Monday <br> 12/4 |  Tuesday <br>12/5    | Wednesday<br>  12/6 | Thursday <br> 12/7 | Friday <br> 12/8 |Saturday<br> 12/9 | Sunday<br> 12/10
|--------|-------- |--------|-------- |--------|--------|--------|--------    
**Assignment due** |  | | Post question to discussion board<br>Meet with Prof. K to discuss project ideas (by appt) | Answer a question on discussion board | Meet with Prof. K to discuss project ideas (by appt)| |

Commit final project report by Wednesday, December 13
